### ISSUE TITLE
Feature Request - Enable History Timestamps and History record per command

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/kali-setup-script#5]
Enable history timestamps, e.g. - https://www.linuxuprising.com/2019/07/bash-history-how-to-show-timestamp-when.html

Also enable history saving to the file per command, rather than on session exit.

Also add unlimited history: https://stackoverflow.com/questions/9457233/unlimited-bash-history

https://sanctum.geek.nz/arabesque/better-bash-history/
also this - `PROMPT_COMMAND='history -a'`

**Comment by aconite33** [comment]
We also need to modify that the time stamps are recorded in UTC time.

**Comment by TheTechromancer** [comment]
Added all these options (and to my best ability, their ZSH equivalents), since offsec in the infinite wisdom has dropped bash and replaced it with zsh as the default shell.  Classic offsec ... they also inserted emojis into the terminal prompt, so, there's that.  I'm livid.

![image](https://user-images.githubusercontent.com/20261699/109712682-58b7ed80-7b6e-11eb-8116-f710640b6566.png)

https://github.com/blacklanternsecurity/kali-setup-script/commit/5c73f117bb298dc00d9b2ce3dbe47a033b4f0494
